### ISSUE TITLE
Resources proxies

### ISSUE THREAD

**Issue by fabiencastan** [shuttleofx/ShuttleOFX#140]
Currently it is possible to upload all king of images like tiff, exr, ... This works fine as all thoses images are supported by tuttleofx.
The problem is that those specific formats are not supported by web browsers, so instead of using them directly for display puposes, we need to use proxies.
We need a thumbnail proxy for the resources menu in the bottom and also a full resolution jpg proxy (with a low level of compression) for image comparison.

**Comment by MarcAntoine-Arnaud** [comment]
Or the other way is to redefine the display into the webpage.
You can download data and display by yourself using canvas, but requires a little bit of work...
But it can be interesting especially for EXR to view large dynamic.
