### ISSUE TITLE
Add EXR format to download options

### ISSUE THREAD

**Issue by Anixen** [shuttleofx/ShuttleOFX#173]

**Comment by Anixen** [comment]
Add EXR format to the dowload options into the dowload modal.
Shouldn't be much an issue since the renderer is able to guess the best writer from filename extension, which we can swap before sending a request to the renderer.

I just leave this issue here for a moment to see if more format ideas/wishes come to mind.

**Comment by fabiencastan** [comment]
Useful to add DPX.

**Comment by fabiencastan** [comment]
Add an option to download input image in the original format.
