### ISSUE TITLE
WIKI UX

### ISSUE THREAD

**Issue by fabiencastan** [shuttleofx/ShuttleOFX#214]
- [x] rename the tab from WIKI to DOCUMENTATION
  - [ ] need a way to say that we use markdown
    Maybe we can initialize the text with a markdown template when someone create a new wiki.
  - [ ] add a link to markdown documentation

**Comment by ghost** [comment]
Added to my 'to do' list !
And I agree with the markdown template, **toldly**.
Ok for the markdown doc, seems natural.

I'm on it !

**Comment by julietteTaka** [comment]
#241
