### ISSUE TITLE
Plugins menu hierarchy

### ISSUE THREAD

**Issue by fabiencastan** [shuttleofx/ShuttleOFX#227]
Currently the hierarchy is not clear mainly because there are some misalignments.

**Comment by Olivier-Daire** [comment]
I'm not sure to fully understand what you mean, would something like this be better ? 
![image](https://cloud.githubusercontent.com/assets/6728295/13565163/b2551582-e44e-11e5-815e-86dacb423dbd.png)

**Comment by fabiencastan** [comment]
Yes
