### ISSUE TITLE
Use plugin raw identifier and version in URL

### ISSUE THREAD

**Issue by julietteTaka** [shuttleofx/ShuttleOFX#65]
Instead of the index.

**Comment by MarcAntoine-Arnaud** [comment]
Can cause problem. Raw identifier is not unique, and may be confusing between plugins.
Routes need to have unique identifiers.
For example which plugin will you display if you have 2 or more versions of the same plugin ?
If 2 contructors have developed the same plugin (blur, resize, ...).
No constraints exists on rawidentifier in the OpenFX, and it's normal.

In your case you can add filtering/research parameters.
The API will be defined like:
/plugins => return paginated plugins
/plugins?rawidentifierlike=blur&sort=asc
/plugins/:uuid => get a specific plugin by it's ID.

**Comment by julietteTaka** [comment]
I may have used the wrong word, I was thinking about the rawidentifier given by the getRawIdentifier() function used by TuttleOFX.
This function returns the pluginIdentifier of a plugin, which is unique.

http://tuttleofx.github.io/TuttleOFX-doxygen/d2/db2/OfxhPluginDesc_8cpp_source.html

http://openfx.sourceforge.net/Documentation/1.3/Doxygen/structOfxPlugin.html#a3f4e9e1091c634b141e19dd848cdaa02

**Comment by MarcAntoine-Arnaud** [comment]
I think about the same parameter. But it's not unique. It's possible to have 2 plugins with the same RawIdentifier. You can try with 2 plugins with differents versions, and see ...

**Comment by julietteTaka** [comment]
Managing different versions is the next step ;)
maybe the route can be 
/plugins/rawId/version ?

**Comment by MarcAntoine-Arnaud** [comment]
But you can also have 2 plugins with the same RawIdentifier, but with 2 providers.
For example lot of resize plugin can be found, with differents quality/algorithms.
It's not possible to use the route like that.

the version will be also a research parameter:
/plugins?rawidentifierlike=blur&version=1.0

in filtering parameters, it's usefull to have:
rawidentifier to select the absolute name
rawidentifierlike to search a part of the name

remark: to be RESTful compliant, you need to define your route: /plugins/:rawid/versions/:version

**Comment by MarcAntoine-Arnaud** [comment]
lot of persons have the same problem, like music platforms.
If you look on Deezer, the route for an artist is: http://www.deezer.com/artist/640
It's not possible to have http://www.deezer.com/artist/:artist_name
Because artiste name is a string, and maybe not unique.
Here 640 is the internal ID used by Deezer to identify this artist.

**Comment by fabiencastan** [comment]
Yes, you're right we need the version. With rawIdentifier and version we are able to identify a plugin uniquely.

If the rawIdentifier is not unique, it will fail in all OFX hosts. For example, in the nuke file format, it stores the rawIdentifier and the version to be able to reload the graph.
So we need to add a check when we upload a new plugin and generate an error if the plugin already exist. Currently there is no error if we upload the same plugin multiple times and that's a problem.

**Comment by julietteTaka** [comment]
https://github.com/shuttleofx/ShuttleOFX/pull/101

**Comment by julietteTaka** [comment]
https://github.com/shuttleofx/ShuttleOFX/pull/101
Versionning isn't supported yet.
